### ISSUE TITLE
logging: Name filename is not defined for FileHandler with delay.

### ISSUE THREAD

**Issue by stlehmann** [pfalcon/micropython-lib#19]
When using `logging.FileHandler` with file opening  deferred until the first call to emit() (`delay=True`) there will be the following error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/root/.micropython/lib/logging/__init__.py", line 59, in warning
      File "/root/.micropython/lib/logging/__init__.py", line 50, in log
      File "/root/.micropython/lib/logging/__init__.py", line 134, in emit
    NameError: name 'filename' isn't defined

The cause of the error is that `filename` and `mode` are referenced as variables and not as properties of `StreamHandler`.

**Comment by stlehmann** [comment]
I introduced this error myself so it' s only fair I also provide the proper fix, here.
